[bindings]
root.toggle_section = ["tab", "i"]
root.move_up = ["e", "up"]
root.move_down = ["a", "down"]
# root.move_up_line = ["Ⴍ+Ⴣ+Ⴓ", "ctrl+up"]
root.move_up_line = ["ctrl+e", "ctrl+up"]
root.move_down_line = ["ctrl+a", "ctrl+down"]
root.move_prev_section = ["alt+a", "alt+up"]
root.move_next_section = ["alt+e", "alt+down"]
root.move_parent_section = ["alt+h", "alt+left", "h"]
